### ISSUE TITLE
hi,运行出错

### ISSUE THREAD

**Issue by prlei** [paascloud/paascloud-login-web#1]
npm install 没有问题
npm run dev 问题：
⇒  npm run dev

> paascloud-login-web@1.0.0 dev /Users/leic/hepbum/temp/nodetest/paascloud-login-web
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 10% building modules 1/1 modules 0 activeevents.js:136
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND dev-login.paascloud.net
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! paascloud-login-web@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the paascloud-login-web@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-05-05T13_57_40_572Z-debug.log

log文件错误内容：
18 verbose node v9.2.0
19 verbose npm  v6.0.0
20 error code ELIFECYCLE
21 error errno 1
22 error paascloud-login-web@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
22 error Exit status 1
23 error Failed at the paascloud-login-web@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

是版本问题么？晕乎乎......

**Comment by tomuGo** [comment]
把启动配置改一下就ok了

**Comment by prlei** [comment]
这回答 我给18分，并拆成666送给你。。。。

**Comment by zzhignore1** [comment]
> 把启动配置改一下就ok了

具体要怎么改呢？

**Comment by chuck54430** [comment]
怎么修改？望解答。

**Comment by chuck54430** [comment]
修改config/index.js文件host 和port配置。

![image](https://user-images.githubusercontent.com/21100173/51881705-103e0c80-23b7-11e9-9682-cfbe19cc84d6.png)
