### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by chuck54430** [paascloud/paascloud-login-web#3]
npm run dev 报错：
```
`"C:\Program Files\JetBrains\WebStorm 2018.2\bin\runnerw.exe" "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run dev --scripts-prepend-node-path=auto

> paascloud-login-web@1.0.0 dev E:\spaceWebStorm\1\paascloud-login-web-master
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

  0% compiling
 10% building modules 1/1 modules 0 activeevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost 
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! paascloud-login-web@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the paascloud-login-web@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wangpengchong\AppData\Roaming\npm-cache\_logs\2019-01-29T03_08_48_409Z-debug.log`
```

**Comment by chuck54430** [comment]
据说需要修改配置文件？具体修改什么地方？
